name: E2E tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Bundle
        run: yarn package

      - name: Run tests
        uses: ./
        env:
          SEARCH: iPhone
        with:
          directory: 'ci'
          lynqa-api-key: ${{ secrets.LYNQA_API_KEY }}
          lynqa-api-url: 'https://api.lynqa.smartesting.com'
